raise CustomError.new(foo), 'argh'